# Generated by Django 4.2.5 on 2023-10-04 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubnetPingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_ip", models.CharField()),
                ("destination", models.CharField()),
                ("type", models.CharField()),
                ("status", models.BooleanField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 10, 4, 1, 17, 25, 678338, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
